version: "3.8"

services:

  prometheus:
    image: prom/prometheus
    container_name: sentinel-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml