spring:
  application:
    name: sentinel-ai
  datasource:
    url: jdbc:postgresql://localhost:5433/sentinel_ai
    username: sentinel
    password: your_password

  jpa:
    jpa:
      open-in-view: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    show-sql: true

  flyway:
    enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus